name: dapackages_example
description: Example code for the dapackages library.
version: 1.4.0
homepage: https://github.com/mauriciotogneri/dapackages

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  yaml: ^2.2.1
  http: ^0.12.2