name: dapackages_example
description: Example code for the dapackages library.
version: 1.5.0-nullsafety.0
homepage: https://github.com/mauriciotogneri/dapackages

environment:
  sdk: ">=2.12.0-133.7.beta <3.0.0"

dependencies:
  yaml: ^2.2.1
  http: ^0.12.2