name: dapackages_example
description: Example code for the dapackages library.
version: 1.6.0
homepage: https://github.com/mauriciotogneri/dapackages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  yaml: ^3.1.0